### ISSUE TITLE
Checkbox and Radio Inline layout is missing

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#40]
Was in design, can't find in layout.

<img width="603" alt="02_03_editor_components_jpg" src="https://user-images.githubusercontent.com/10811565/83978369-af5e0700-a90f-11ea-8d58-b0b407ac2788.png">

**Comment by epicformbuilder** [comment]
There is no radio layout anywhere at all

**Comment by dubovds** [comment]
added

**Comment by epicformbuilder** [comment]
How about not squeezing, but moving checkboxes/radios on a new line instead?

![Document](https://user-images.githubusercontent.com/10811565/84033346-648ccf80-a9a1-11ea-88ce-40048342931f.png)

**Comment by dubovds** [comment]
fixed. 
![image](https://user-images.githubusercontent.com/16684226/84697800-71886080-af57-11ea-8c70-b23256d367cb.png)

**Comment by epicformbuilder** [comment]
Still an issue :(

![Document](https://user-images.githubusercontent.com/10811565/85301506-9416fe00-b4b0-11ea-9418-9ea7bc0b98a2.png)

![DevTools_-_localhost_3000_editor_4625e1f1-0698-4bea-ac1f-6a2e2d3d88e2_fields_from__dashboard_forms-and-responses](https://user-images.githubusercontent.com/10811565/85301597-adb84580-b4b0-11ea-9106-2f0d1cf39524.png)
